// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ppaanngggg/MagicConch/ent/system"
)

// System is the model entity for the System schema.
type System struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// System holds the value of the "system" field.
	System string `json:"system,omitempty"`
	// ClickTime holds the value of the "click_time" field.
	ClickTime time.Time `json:"click_time,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*System) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case system.FieldID:
			values[i] = new(sql.NullInt64)
		case system.FieldSystem:
			values[i] = new(sql.NullString)
		case system.FieldCreateTime, system.FieldUpdateTime, system.FieldClickTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type System", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the System fields.
func (s *System) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case system.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case system.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				s.CreateTime = value.Time
			}
		case system.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				s.UpdateTime = value.Time
			}
		case system.FieldSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system", values[i])
			} else if value.Valid {
				s.System = value.String
			}
		case system.FieldClickTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field click_time", values[i])
			} else if value.Valid {
				s.ClickTime = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this System.
// Note that you need to call System.Unwrap() before calling this method if this System
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *System) Update() *SystemUpdateOne {
	return NewSystemClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the System entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *System) Unwrap() *System {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: System is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *System) String() string {
	var builder strings.Builder
	builder.WriteString("System(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("create_time=")
	builder.WriteString(s.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(s.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("system=")
	builder.WriteString(s.System)
	builder.WriteString(", ")
	builder.WriteString("click_time=")
	builder.WriteString(s.ClickTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Systems is a parsable slice of System.
type Systems []*System
