// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppaanngggg/MagicConch/ent/predicate"
	"github.com/ppaanngggg/MagicConch/ent/system"
)

// SystemUpdate is the builder for updating System entities.
type SystemUpdate struct {
	config
	hooks    []Hook
	mutation *SystemMutation
}

// Where appends a list predicates to the SystemUpdate builder.
func (su *SystemUpdate) Where(ps ...predicate.System) *SystemUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *SystemUpdate) SetUpdateTime(t time.Time) *SystemUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetSystem sets the "system" field.
func (su *SystemUpdate) SetSystem(s string) *SystemUpdate {
	su.mutation.SetSystem(s)
	return su
}

// SetClickTime sets the "click_time" field.
func (su *SystemUpdate) SetClickTime(t time.Time) *SystemUpdate {
	su.mutation.SetClickTime(t)
	return su
}

// SetNillableClickTime sets the "click_time" field if the given value is not nil.
func (su *SystemUpdate) SetNillableClickTime(t *time.Time) *SystemUpdate {
	if t != nil {
		su.SetClickTime(*t)
	}
	return su
}

// Mutation returns the SystemMutation object of the builder.
func (su *SystemUpdate) Mutation() *SystemMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SystemUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks[int, SystemMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SystemUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SystemUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SystemUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SystemUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := system.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
}

func (su *SystemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(system.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.System(); ok {
		_spec.SetField(system.FieldSystem, field.TypeString, value)
	}
	if value, ok := su.mutation.ClickTime(); ok {
		_spec.SetField(system.FieldClickTime, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SystemUpdateOne is the builder for updating a single System entity.
type SystemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *SystemUpdateOne) SetUpdateTime(t time.Time) *SystemUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetSystem sets the "system" field.
func (suo *SystemUpdateOne) SetSystem(s string) *SystemUpdateOne {
	suo.mutation.SetSystem(s)
	return suo
}

// SetClickTime sets the "click_time" field.
func (suo *SystemUpdateOne) SetClickTime(t time.Time) *SystemUpdateOne {
	suo.mutation.SetClickTime(t)
	return suo
}

// SetNillableClickTime sets the "click_time" field if the given value is not nil.
func (suo *SystemUpdateOne) SetNillableClickTime(t *time.Time) *SystemUpdateOne {
	if t != nil {
		suo.SetClickTime(*t)
	}
	return suo
}

// Mutation returns the SystemMutation object of the builder.
func (suo *SystemUpdateOne) Mutation() *SystemMutation {
	return suo.mutation
}

// Where appends a list predicates to the SystemUpdate builder.
func (suo *SystemUpdateOne) Where(ps ...predicate.System) *SystemUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SystemUpdateOne) Select(field string, fields ...string) *SystemUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated System entity.
func (suo *SystemUpdateOne) Save(ctx context.Context) (*System, error) {
	suo.defaults()
	return withHooks[*System, SystemMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SystemUpdateOne) SaveX(ctx context.Context) *System {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SystemUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SystemUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SystemUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := system.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
}

func (suo *SystemUpdateOne) sqlSave(ctx context.Context) (_node *System, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "System.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, system.FieldID)
		for _, f := range fields {
			if !system.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != system.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(system.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.System(); ok {
		_spec.SetField(system.FieldSystem, field.TypeString, value)
	}
	if value, ok := suo.mutation.ClickTime(); ok {
		_spec.SetField(system.FieldClickTime, field.TypeTime, value)
	}
	_node = &System{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
