// Code generated by ent, DO NOT EDIT.

package conversation

const (
	// Label holds the string label denoting the conversation type in the database.
	Label = "conversation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMessages holds the string denoting the messages field in the database.
	FieldMessages = "messages"
	// Table holds the table name of the conversation in the database.
	Table = "conversations"
)

// Columns holds all SQL columns for conversation fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldMessages,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
