// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function One(arg1) {
  return window['go']['main']['App']['One'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
