// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:any):Promise<any>;

export function GetSettings():Promise<any>;

export function Render(arg1:string):Promise<string>;

export function SaveSettings(arg1:any):Promise<void>;
