// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:any):Promise<any>;

export function DeleteConversation(arg1:number):Promise<void>;

export function GetConversation(arg1:number):Promise<any>;

export function GetSettings():Promise<any>;

export function ListConversations(arg1:string):Promise<Array<any>>;

export function SaveConversation(arg1:any):Promise<any>;

export function SaveSettings(arg1:any):Promise<void>;
