// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Render(arg1) {
  return window['go']['main']['App']['Render'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
