// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1:any):Promise<any>;

export function GetSettings():Promise<any>;

export function List():Promise<Array<any>>;

export function One(arg1:number):Promise<any>;

export function Save(arg1:any):Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;
