name: release
on:
  release:
    types: [ published ]

jobs:
  release:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        platform: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: build macOS
        if: matrix.platform == 'macos-latest'
        run: |
          wails build -platform=darwin/${{ matrix.arch }}
      - name: build windows
        if: matrix.platform == 'windows-latest'
        run: |
          wails build -platform=windows/${{ matrix.arch }}
      - name: build linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          wails build -platform=linux/${{ matrix.arch }}
      - name: upload artifacts macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-darwin-${{ matrix.arch }}
          path: build/bin/*
      - name: upload artifacts windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-windows-${{ matrix.arch }}
          path: build/bin/*
      - name: upload artifacts linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-linux-${{ matrix.arch }}
          path: build/bin/*
