name: release
on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
            sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Check Wails deps
        run: |
          wails doctor
      - name: Build Wails app
        run: |
          wails build
      - name: upload artifacts macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-binaries-macos
          path: build/bin/*
      - name: upload artifacts windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-binaries-windows
          path: build/bin/*
      - name: upload artifacts linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wails-binaries-linux
          path: build/bin/*
