name: release
on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Wails
        run: |
          wails build -platform=darwin/amd64,darwin/arm64,windows/amd64,windows/arm64,linux/amd64,linux/arm64
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wails-binaries
          path: build/bin/*
