// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
